# Generated by Django 5.2.4 on 2025-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationcode',
            old_name='codes',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
