# Generated by Django 5.2.4 on 2025-08-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationjob',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
